### ISSUE TITLE
Possible to use as a demo code?

### ISSUE THREAD

**Issue by sonicviz** [kjetilhau/meteor-skeleton#1]
Hi kjetilhau!
Nice boilerplate! thanks.

I'm writing a blog post on Meteor for http://ziptask.com/ and wanted to demonstrate a couple of code examples, including app structure which you have nicely done here.

Could I use your project for this? It'll be some code snippets and I'll include a link to the project.
Couldn't find a contact on your github so posted as an issue, if that's ok.

ty.
Paul

**Comment by kjetilhau** [comment]
Hey Paul, thanks for the kind words!

Go ahead and use it any way you like :)

**Comment by sonicviz** [comment]
awesome. ty!

**Comment by sonicviz** [comment]
Hi Kjetil,

Article is now up at https://www.ziptask.com/Meteorjs-A-New-Paradigm-for-Connected-Client-Apps 

Thanks!

Cheers,

Paul
