### ISSUE TITLE
how to use permissions (permissions.js ) ?

### ISSUE THREAD

**Issue by LDubya** [kjetilhau/meteor-skeleton#5]
Hey guys, great boilerplate. Very well thought-out. There's just one thing I can't find however...

I'm trying to find an example of how to implement the permissions from permissions.js (canEditItem, canRemoveItem, isAdmin). They are defined, but it doesn't look like they're used anywhere. Thanks! I've linked the file for reference.

[imports/modules/permissions.js](https://github.com/kjetilhau/meteor-skeleton/blob/master/imports/modules/permissions.js)

**Comment by kjetilhau** [comment]
Hey, and thanks for the kind words. The permission module is just an example of how it could be done. There is currently no account stuff implemented, but it should be pretty straight-forward to use them if you use the accounts-base package. For example, you can fetch the userId with this.userId on the server and then provide it as a parameter on one of the module functions.
